### ISSUE TITLE
way to probe bears for needed settings

### ISSUE THREAD

**Issue by sils1297** [sils1297/coala#111]
we currently have get_needed_settings but it would be nice to have something like get_minimal_needed_settings() and get_needed_settings() on top of it. This way the user can find out what settings are possible for this bear and not only which ones are needed.

What do you think?

**Comment by cw1** [comment]
Your last comment sounds good. Is this the way we can produce a help massage for the user for any giving bear? What kind of syntax would you like to prefer for the documentation comment?

**Comment by sils1297** [comment]
usual doc comment like we use all day long in coala.

**Comment by sils1297** [comment]
first draft of documentation parser is here: https://github.com/sils1297/coala/blob/wip/extract_needed_params/coalib/parsing/DocumentationCommentParser.py
I'm open to suggestions for simplifications.

**Comment by sils1297** [comment]
interesting:
```
>>> def test(var1, var2: test="t"):
...   pass
... 
>>> getfullargspec(test)
FullArgSpec(args=['var1', 'var2'], varargs=None, varkw=None, defaults=('t',), kwonlyargs=[], kwonlydefaults=None, annotations={'var2': <function test at 0x7f5c45a6fc80>})
```

**Comment by sils1297** [comment]
it works:
```python
>>> from coalib.settings.FunctionMetadata import FunctionMetadata
>>> def test(p1, p2="test", p3=5):
...   """
...   tests something
... 
...   :param p2: its a test value
...   :return nothing.
...   """
...   pass
... 
>>> fm=FunctionMetadata.from_function(
... test)
>>> fm.name
'test'
>>> fm.desc
'tests something'
>>> fm.retval_desc
'nothing.'
>>> fm.non_optional_params
{'p1': 'No description given.'}
>>> fm.optional_params
{'p2': "its a test value (Optional, defaults to 'test'.)", 'p3': "No description given. (Optional, defaults to '5'.)"}

```

**Comment by sils1297** [comment]
began implementation on #150

**Comment by sils1297** [comment]
we now have this implemented in the SettingsCreatable, will migrate this to the bears soon. However we'll need code duplication avoidance strategies for this, I don't wanna copy it.

**Comment by sils1297** [comment]
```
lasse@lsmobfed21 ~/prog/gnome/srcn/gnome-boxes (git)-[master] % coala
Please enter a value for the setting "UseSpaces" (('True if spaces are to be used instead of tabs.', <class 'bool'>)) needed by SpaceConsistencyBear:
```
Works on #150. Outputter needs to be adjusted a bit though but Fabians creating the ConsoleOutputter from scratch anyway.
