### ISSUE TITLE
temporary save cli parameter

### ISSUE THREAD

**Issue by sils1297** [sils1297/coala#158]
we need a cli parameter that allows to save the file without writing the save=true into the file thus saving every time since then.

**Comment by sils1297** [comment]
I added a save_always setting to CliParams wiki page. Thus I'm making the save param non-persistent!

**Comment by sils1297** [comment]
save will take precedence over save_always

**Comment by sils1297** [comment]
so if save_always is true and user specifies save via CLI to another file the latter will be taken

**Comment by sils1297** [comment]
ok I'm not sure if we even want the save_always arg but that will have to wait and get its own bug.

**Comment by sils1297** [comment]
implemented in #150

**Comment by AbdealiJK** [comment]
This issue was moved to coala-analyzer/coala-bears#775

**Comment by AbdealiJK** [comment]
Sorry for the "move". https://github-issue-mover.appspot.com/ is misbehaving.
